In [10]:
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
student_marks = [78, 47, 96, 55, 34]
hetero_list =  [1,2,3.0, 'text', True,3+2j ]


In [11]:
student_marks = [78, 47, 96, 55, 34]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)


[83, 52, 101, 60, 39]


In [12]:
%%time
list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
    


CPU times: total: 391 ms
Wall time: 417 ms


In [13]:
%%time
import numpy as np

a = np.arange(1,1000000)
b = np.arange(2,1000001)
c = a+b


CPU times: total: 203 ms
Wall time: 318 ms


In [14]:
import numpy as np


In [15]:
import numpy as np
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr


array([78, 92, 36, 64, 89])

In [16]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
horsepower_arr


array([130, 165, 150, 150, 140])

In [17]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr


array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [18]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.shape


(3, 5)

In [19]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.dtype


dtype('int32')

In [20]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)


[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [3]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Mean horsepower = ",np.mean(horsepower_arr))


NameError: name 'np' is not defined

In [4]:
import numpyas np


In [5]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Mean horsepower = ",np.mean(horsepower_arr))


Mean horsepower =  147.0


In [6]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Median horsepower = ",np.median(horsepower_arr))


Median horsepower =  150.0


In [7]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Minimum horsepower: ", np.min(horsepower_arr))
print("Maximum horsepower: ", np.max(horsepower_arr))


Minimum horsepower:  130
Maximum horsepower:  165


In [9]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print(np.argmin(horsepower_arr))
print(np.argmax(horsepower_arr))


0
1


In [2]:
import numpy as np
horsepower = np.array([140, 170, 150, 200, 155, 160, 120, 130])
x = np.where(horsepower>=150)
print(x)
print(horsepower[x])


(array([1, 2, 3, 4, 5], dtype=int64),)
[170 150 200 155 160]


In [8]:
student_marks = np.array([[67,45],[90,92],[66,72],[32,40]])
student_marks

array([[67, 45],
       [90, 92],
       [66, 72],
       [32, 40]])

In [10]:
student_marks = np.array([[67,45],[90,92],[66,72],[32,40]])
add_marks = np.array([5,10])
student_marks1 = np.add(add_marks,student_marks)
student_marks1

array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])

In [12]:
np.ones([2])

array([1., 1.])

In [3]:
import numpy as np
steps = np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
print(steps)
steps_walked = np.array([6012,7079,6886,7230,4598,5564,6971,7763,8032,9569])

add_step = np.array([0,2000])
step2 = np.add(steps,add_step)
print('steps after 7pm =',step2)


x = np.where(steps[:,1]>9000)
print(steps2[x])


sorted = step2[:,1].argsort()
step2[sorted]

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]
steps after 7pm = [[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


NameError: name 'steps2' is not defined

In [1]:
import pandas as pd
x = pd.DataFrame([steps2])
x1 = x+1000
x

NameError: name 'steps2' is not defined

In [35]:
import numpy as np

In [6]:
x = np.where(steps2[:,1]>9000)
print(steps2[x])


[[    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [32]:
zz = step2[:,1].argsort()
step2[zz]

array([[    5,  6598],
       [    6,  7564],
       [    1,  8012],
       [    3,  8886],
       [    7,  8971],
       [    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [40]:
import numpy as np
#sum
arr = np.array([[1, 2], [3, 4]])
print(arr)
print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [41]:
#mean
arr = np.array([[1, 2], [3, 4]])
print(arr)
print(np.mean(arr))
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))

[[1 2]
 [3 4]]
2.5
[2. 3.]
[1.5 3.5]


In [42]:
#max
arr = np.array([[1, 2], [3, 4]])
print(arr)
print(np.max(arr))
print(np.max(arr, axis=0)) 
print(np.max(arr, axis=1)) 

#min
print(np.min(arr)) 
print(np.min(arr, axis=0)) 
print(np.min(arr, axis=1))

[[1 2]
 [3 4]]
4
[3 4]
[2 4]
1
[1 2]
[1 3]


In [43]:
#median
arr = np.array([[1, 2], [3, 4]])

print(np.median(arr))
print(np.median(arr, axis=0)) 
print(np.median(arr, axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [44]:
#prod
arr = np.array([[1, 2], [3, 4]])
print(np.prod(arr))
print(np.prod(arr, axis=0))
print(np.prod(arr, axis=1))

24
[3 8]
[ 2 12]


In [45]:
#std
arr = np.array([[1, 2], [3, 4]])
print(np.std(arr))
print(np.std(arr, axis=0))
print(np.std(arr, axis=1))

1.118033988749895
[1. 1.]
[0.5 0.5]


In [63]:
np.sqrt(((1-2.5)*(1-2.5)+(2-2.5)*(2-2.5)+(3-2.5)*(3-2.5)+(4-2.5)*(4-2.5))/4)

1.118033988749895

In [64]:
np.sqrt(((1-2)*(1-2)+(3-2)*(3-2))/2)

1.0

In [47]:
#var
arr = np.array([[1, 2], [3, 4]])
print(np.var(arr)) 
print(np.var(arr, axis=0))
print(np.var(arr, axis=1))

1.25
[1. 1.]
[0.25 0.25]


In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [49]:
arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2
print(result)

[3 3 3]


In [50]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(result)

[ 4 10 18]


In [51]:
arr1 = np.array([4, 6, 8])
arr2 = np.array([2, 3, 4])
result = arr1 / arr2
print(result)

[2. 2. 2.]


In [82]:
arr = np.array([2, 3, 4])
result = arr ** 2
print(result) 

[ 4  9 16]


In [53]:
arr = np.array([4, 9, 16])
result = np.sqrt(arr)
print(result)

[2. 3. 4.]


In [54]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 3])
result = arr1 == arr2
print(result) 

[False  True  True]


In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_mean = np.mean(arr)
result_std = np.std(arr, axis=1)
result_sum = np.sum(arr, axis=0)
print(result_mean)
print(result_std) 
print(result_sum)

3.5
[0.81649658 0.81649658]
[5 7 9]


In [65]:
arr = np.array([2.3, 4.7, 6.1])
result = np.round(arr)
print(result)

[2. 5. 6.]


In [66]:
arr = np.array([2, 3, 4])
result = np.power(arr, 2)
print(result)

[ 4  9 16]


In [67]:
arr = np.array([1, 5, 10])
result = np.where(arr < 5, arr, 0)
print(result)

[1 0 0]


In [68]:
arr = np.array([1, 2, 3, 4, 5])
result = np.cumsum(arr)
print(result)

[ 1  3  6 10 15]


In [69]:
arr = np.array([3, 1, 4, 2, 5])
result = np.sort(arr)
print(result)

[1 2 3 4 5]


In [70]:
S_X = np.array([[2, 5, 6, 5],[4, 8, 6, 5]])
S_Y = np.array([[6, 7, 5, 9],[7, 5, 6, 4]])
quarterly_difference = S_Y - S_X
print(quarterly_difference)

[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [71]:
less_than_2 = S_X < 2
print(less_than_2)

[[False False False False]
 [False False False False]]


In [73]:
X_cumsum = np.cumsum(S_X, axis = 1)
print(X_cumsum)
print( X_cumsum >= 8)

[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]


In [74]:
Y_cumsum = np.cumsum(S_Y, axis = 1)
print(Y_cumsum)
print( Y_cumsum >= 8)


[[ 6 13 18 27]
 [ 7 12 18 22]]
[[False  True  True  True]
 [False  True  True  True]]


In [75]:
yearly_mean_X = np.mean(S_X, axis=1)
print(yearly_mean_X)

[4.5  5.75]


In [76]:
quarterly_mean_Y = np.mean(S_Y, axis=0)
print(quarterly_mean_Y)

[6.5 6.  5.5 6.5]


In [77]:
#map
numbers = [1, 2, 3, 4, 5]
# Squaring each number using map()
squared_numbers = map(lambda x: x ** 2, numbers)
print(list(squared_numbers))

[1, 4, 9, 16, 25]


In [78]:
#filter
numbers = [1, 2, 3, 4, 5]
# Filtering even numbers using filter()
even_numbers = filter(lambda x: x % 2 == 0, numbers)
print(list(even_numbers))

[2, 4]


In [79]:
#reduce
from functools import reduce
numbers = [1, 2, 3, 4, 5]
# Summing all the numbers using reduce()
sum_of_numbers = reduce(lambda x, y: x + y, numbers)
print(sum_of_numbers)

15


In [80]:
#Lambda functions:
# Squaring a number using a lambda function
square = lambda x: x ** 2
print(square(5))


25
